#!/bin/bash
echo "========================================"
echo "  豆瓣 Cookie 获取指南"
echo "========================================"
echo ""
echo "步骤："
echo ""
echo "1. 打开浏览器（推荐 Chrome / Edge）"
echo "2. 访问 https://www.douban.com 并登录"
echo "3. 按 F12 打开开发者工具"
echo "4. 切换到「网络」(Network) 标签"
echo "5. 刷新页面（Ctrl+R / Cmd+R）"
echo "6. 点击列表中的第一个请求（通常是页面 URL 本身）"
echo "7. 在右侧面板找到「请求标头」(Request Headers)"
echo "8. 找到 Cookie 字段，复制整个值"
echo ""
echo "使用方式："
echo "  python3 ~/Documents/movie-fetch/fetch_movies.py --cookie '粘贴的cookie' ..."
echo ""
echo "注意事项："
echo "  - Cookie 有效期通常几周，过期需重新获取"
echo "  - 不要提交到 Git 仓库"
echo "  - Cookie 包含登录凭证，注意保密"
echo "  - 如果 403，尝试重新登录豆瓣获取新 Cookie"
echo ""
